#单节点服务配置
singleServerConfig:
  # 连接池容量
  connectionPoolSize: 64
  # 最小空闲连接数
  connectionMinimumIdleSize: 32
  # 连接超时：（单位：毫秒）
  connectTimeout: 10000
  # 连接空闲超时：（单位：毫秒）
  idleConnectionTimeout: 10000
  # Ping 节点超时：（单位：毫秒）
  pingTimeout: 1000
  # 命令等待超时：（单位：毫秒）
  timeout: 3000
  # 命令失败重试次数
  retryAttempts: 3
  # 命令重试发送时间间隔：（单位：毫秒）
  retryInterval: 1500
  # 重新连接时间间隔：（单位：毫秒）
  reconnectionTimeout: 3000
  # 执行失败最大次数
  failedAttempts: 3
  # 发布和订阅连接的最小空闲连接数
  subscriptionConnectionMinimumIdleSize: 1
  # 发布和订阅连接池大小
  subscriptionConnectionPoolSize: 50
  # 单个连接最大订阅数量
  subscriptionsPerConnection: 5
  # 节点地址
  address: "redis://192.168.0.65:6379"
  # 节点密码（用于节点身份验证的密码）
  password: root
  # 客户端名称
  clientName: null
  # 数据库编号（尝试连接的数据库编号）
  database: 1
  # 是否启用DNS监测
  #dnsMonitoring: false
  # DNS监测时间间隔：（单位：毫秒）
  #dnsMonitoringInterval: 5000
# 线程池数量
threads: 0
# Netty线程池数量
nettyThreads: 0
# 设置Redisson序列化编码
codec: !<org.redisson.codec.JsonJacksonCodec> {}
# 传输模式
transportMode: NIO
